name: size-comment
on:
  workflow_run:
    workflows: [size-build]
    types: [completed]

permissions:
  pull-requests: write
  issues: write
  actions: read

jobs:
  comment:
    # Only run if the build workflow succeeded and was triggered by a pull request
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [nuxi, nuxt-cli, create-nuxt]
    steps:
      - name: 🔍 Get PR number
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pulls = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.payload.workflow_run.head_sha,
            });
            if (pulls.data.length > 0) {
              return pulls.data[0].number;
            }
            
      - name: ⏬ Download artifacts from workflow run
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: 📊 Compare sizes
        uses: twk3/rollup-size-compare-action@v1.2.0
        env:
          PR_NUMBER: ${{ steps.pr.outputs.result }}
        with:
          title: ${{ matrix.package }} size comparison
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: ./head-stats/${{ matrix.package }}/stats.json
          base-stats-json-path: ./base-stats/${{ matrix.package }}/stats.json
